network:
  ethernets:
    ens33:
      addresses:
      - 192.168.0.122/24
      gateway4: 192.168.0.1
      nameservers:
        addresses:
        - 8.8.8.8
        - 8.8.4.4
        - 192.168.0.1
        search: []
  version: 2
